[package]
name = "roguelike"
version = "0.1.0"
authors = ["I.R. Springborn <springborni9385@my.uwstout.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.7" }